# Example 25
apiVersion: v1
kind: Service
metadata:
  name: kuard-rs-test-service
spec:
  externalIPs:
  - 10.128.0.10 
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: kuard-rs-test-pod

