# Example 51
apiVersion: v1
kind: Pod
metadata:
  name: projected-vol-pod
spec:
  containers:
  - name: container-test
    image: busybox
    volumeMounts: 
    - name: all-in-one
      mountPath: "/projected-volume"
      readOnly: true 
    command:
    - sh
    - -c
    - "sleep 10000"
  volumes: 
  - name: all-in-one 
    projected:
      defaultMode: 0400 
      sources:
      - secret:
          name: access-token
          items:
            - key: access-token
              path: access-token 
      - configMap: 
          name: proxy-config
          items:
            - key: proxy
              path: proxy-config
              mode: 0777
      - downwardAPI: 
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "cpu_limit"
              resourceFieldRef:
                containerName: container-test
                resource: limits.cpu

